frgfm/torch-cam

- scripts/cam_example.py
- test/test_cams.py
- torchcam/cams/cam.py
- torchcam/cams/gradcam.py
This PR aims at:
- fixing docstrings
- adding safety checks before computing the activation map
- refactors weight computation
- refactors unittests
_Note: breaking changes are introduced by modifying the `_CAM` signature_
> refactor: Code refactor

- docs/source/conf.py
- torchcam/cams/cam.py
This PR adds Google analytics to verify website, and make it easier to find on Google.
> docs: Added website referencing

- docs/source/cams.rst
- docs/source/index.rst
- docs/source/installing.rst
- torchcam/cams/cam.py
- torchcam/cams/gradcam.py
This PR improves documentation by:
- adding installation instructions
- adding detailed docstring with explanations on each computation method
> docs: Added detailed explanation on CAM computation

- docs/source/cams.rst
- scripts/cam_example.py
- test/test_cams.py
- torchcam/cams/cam.py
This PR introduces a variant of SS-CAM using integration rather than summation by:
- implementing the `ISSCAM`class
- updating documentation
- updating unittests
- updating the sample script
> feat: Added implementation of ISS-CAM

- .github/workflows/main.yml
- mypy.ini
- torchcam/cams/__init__.py
- torchcam/cams/cam.py
- torchcam/cams/gradcam.py
- torchcam/utils.py
This PR adds annotation typing to package and a CI job with mypy verification to close #18.
> style: Added annotation typing to the package

- .github/workflows/doc-deploy.yaml
- .github/workflows/main.yml
- .github/workflows/pkg-upload.yaml
This PR optimizes the usage of cache between jobs to reduce execution time dramatically.
> chore: Optimized cache in CI

- README.md
- scripts/cam_example.py
- test/test_cams.py
- test/test_utils.py
- torchcam/cams/__init__.py
- torchcam/cams/cam.py
- torchcam/cams/gradcam.py
- torchcam/cams/utils.py
This PR introduces the following features:
- added automatic layer resolution for target_layer and fc_layer
- removed unnecessary input_layer for hook mechanism
- updated unittests
- updated example script
- updated README
Successfully merging this PR will close #31
> feat: Added automatic layer name resolution

- test/test_cams.py
- torchcam/cams/gradcam.py
- fixed SmoothGradCAMpp example docstring
- fixed unit tests, and speeded them up
> docs: Fixed example docstring and unittests

- .github/workflows/pkg-upload.yaml
- CONTRIBUTING.md
- README.md
- setup.py
- updates the package version
- updates README & CONTRIBUTING
- fixes conda setup in CI
> chore: Post-release modifications

- README.md
- docs/source/index.rst
- scripts/cam_example.py
- torchcam/cams/utils.py
- fixed automatic layer resolution when on GPU
- refactored example script to showcase layer resolution
- updated README
- updated documentation
> feat: Simplified example script and updated documentation

- CONTRIBUTING.md
- README.md
This PR fixes the usage example in the README and closes #42
> docs: Fixed usage example in README

- README.md
This PR simply fixes the codacy badge URL of the README
> docs: Fixed codacy badge in README

- README.md
- docs/source/cams.rst
- test/test_cams_gradcam.py
- torchcam/cams/gradcam.py
- added implementation of XGrad-CAM
- added it to unittest
- added documentation section
- updated README
> feat: Added support of XGrad-CAM

- docs/build.sh
This PR pins the conf.py for all documentation versions so that the version selector is always displayed.
> docs: Pinned conf.py for all doc versions

- README.md
- demo/app.py
- demo/requirements.txt
- docs/source/index.rst
- completely revamped the README
- added a minimal streamlit demo app
- removed the index section from the documentation
> feat: Added a minimal demo app and improved README

- docs/requirements.txt
- docs/source/cams.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/installing.rst
This PR improved the existing documentation before the upcoming release
> docs: Improved documentation

- .conda/meta.yaml
- requirements.txt
- setup.py
This PR simply updates package requirements and version.
> chore: Updated requirements and version

- .github/workflows/pkg-upload.yaml
- README.md
- docs/build.sh
- docs/source/_static/js/custom.js
- setup.py
- fixed package upload CI jobs
- Updated README CI badge
- Updated documentation versions
- Updated version in `setup.py`
> chore: Made post release modifications

- docs/build.sh
This PR fixes the building CI job of the documentation.
> docs: Fixed doc building script

- scripts/cam_example.py
- added Input image to the final layout
- added the option to specify the number of rows
> feat: Updated example script

- README.md
- demo/app.py
- added class selection
- added default target layer selection
- updated demo screenshot in the README
> feat: Improved demo UX

- test/conftest.py
- test/test_cams_cam.py
- torchcam/cams/cam.py
- added compatibility with an architecture where the final FC layer is replaced by a conv1x1.
- added corresponding unittests
Resolves #68
> feat: Added compatibility of CAM with conv1x1 final layer

- .github/workflows/demo.yml
- .github/workflows/scripts.yml
- .github/workflows/style.yml
This PR simply fixes the name of the CI job checking the demo sanity.
> chore: Fixed demo job name

- .github/ISSUE_TEMPLATE/bug_report.md
- scripts/collect_env.py
- adds an environment collection script
- updates the bug template
> docs: Updated bug template

- .github/workflows/style.yml
- CONTRIBUTING.md
- demo/app.py
- docs/source/conf.py
- scripts/cam_example.py
- scripts/collect_env.py
- scripts/eval_latency.py
- setup.cfg
- test/conftest.py
- torchcam/cams/cam.py
- torchcam/cams/core.py
- torchcam/cams/gradcam.py
- torchcam/cams/utils.py
- torchcam/utils.py
- Reordered imports with isort
- updated CONTRIBUTING
- updated docstrings
- added CI job to enforce isort
> style: Reordered imports with isort and updated CONTRIBUTING

- .github/workflows/docs.yaml
- .github/workflows/main.yml
- docs/requirements.txt
- fixes the docutils dep version constraint since the last release is buggy
- added CI jobs to validate that the documentation is running smoothly
> docs: Fixed documentation build requirements

- docs/source/conf.py
- docs/source/notebooks/latency_benchmark.rst
- docs/source/notebooks/quicktour.rst
This PR adds the notebook source RST files in the documentation and ensures sphinx doesn't build them.
> docs: Added RST files for notebooks

- docs/source/changelog.rst
This PR simply updates the changelog in the documentation.
> docs: Updated changelog

- demo/app.py
- added automatic text strip for multi target names
- added helper message in the demo
> feat: Added text strip for multiple target selection in demo

- scripts/collect_env.py
This PR simply updates the environment collection script
> refactor: Updated environment collection script

- requirements.txt
- tests/test_requirements.py
This PR adds a check for consistency between `setup.py` and `requirements.txt`.
> test: Added a test for requirements consistency

- setup.py
- tests/conftest.py
- tests/requirements.txt
- tests/test_headers.py
- tests/test_methods_activation.py
- tests/test_methods_core.py
- tests/test_methods_gradient.py
- tests/test_methods_utils.py
- tests/test_requirements.py
- tests/test_utils.py
- improves the deps consistency check
- adds a header check
> test: Adds a header check & improves dep consistency check

- .flake8
This PR updates flake8 config to spot unused imports, docstring backslack issues, undefined variables.
> style: Updated flake8 config

- .flake8
- .github/workflows/style.yml
- .isort.cfg
- Makefile
- setup.cfg
- fixes the isort job
- updates the flake8 config
- updates the makefile
> ci: Updated isort config and related CI job

- .github/workflows/scripts.yml
- scripts/cam_example.py
- adds the possibility to pass several CAM methods to the example script
- speeded up the CI job testing the example script
> ci: Speeded up the example script CI check

- .github/release.yml
- .github/verify_labels.py
- .github/workflows/pr-labels.yml
- adds a release note template
- adds a CI job for PR label check
> ci: Added release note template and a job to check PR labels

- CITATION.cff
This PR simply adds the CITATION file to the repo
> docs: Added CITATION file

- requirements.txt
- setup.py
Following up on #148, this PR updates the version specifier of PyTorch.
> chore: Updated PyTorch version specifier

- docs/source/index.rst
This PR simply updates the depth level of the Table of Content for the landing page of the documentation.
> docs: Updated TOC of documentation

- README.md
This PR fixes the codacy badge in the README
> docs: Fixed codacy badge

- CONTRIBUTING.md
- Makefile
- fixes a typo in CONTRIBUTING
- fixes the mypy command in the Makefile
> docs: Fixed typo in CONTRIBUTING

- .github/workflows/style.yml
- Makefile
- pyproject.toml
- fixed pyproject.toml for mypy & isort
- updates CI jobs and Makefile
- fixed isort for api
> style: Updated mypy and isort configs

- Makefile
- README.md
- docs/source/conf.py
- torchcam/methods/activation.py
- torchcam/methods/gradient.py
- torchcam/utils.py
- fixes the README badge for documentation
- fixes the command name in the Makefile
- adds a documentation edit button
- fixes docstring examples for the new theme
> docs: Fixed README badge and updated documentation

- .github/workflows/release.yml
This PR simplifies the environment variable setting in the release job.
> ci: Updated release job

- tests/test_methods_utils.py
This PR fixes isort for the new unittests
> style: Fixed import order

- docs/source/index.rst
This PR simply updates the code screenshot of the documentation landing page.
> docs: Updated landing page screenshot

- .github/workflows/release.yml
- docs/build.sh
- docs/source/_static/js/custom.js
- docs/source/changelog.rst
- setup.py
- fixed the CI release job
- updated the documentation
- updated the version index of the package
> chore: Applied post-release modifications

- .conda/meta.yaml
- docs/source/index.rst
- docs/source/metrics.rst
- scripts/eval_perf.py
- scripts/results.csv
- tests/test_metrics.py
- torchcam/__init__.py
- torchcam/metrics.py
- added average drop and increase in confidence as performance metrics
- added dedicated unittests
- added entries in the documentation
- added evaluation script
- added result CSV
Closes #140
> feat: Added CAM evaluation metric

- .github/FUNDING.yml
This PR adds a sponsor button on the repo.
> ci: Added FUNDING button

- docs/build.sh
This PR cleans up the documentation build script
> docs: Improved documentation build script

- .github/labeler.yml
- .github/workflows/pull_requests.yml
- .github/workflows/tests.yml
- CONTRIBUTING.md
- README.md
- fixes ref to CONTRIBUTING in the README
- adds missing installation step in CONTRIBUTING
- updates the labeler
> docs: Updates README & CONTRIBUTING

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
This PR fixes the label assignment of issue templates.
> ci: Fixes issue templates

- .github/collect_env.py
- .github/verify_labels.py
- demo/app.py
- docs/source/conf.py
- scripts/cam_example.py
- scripts/eval_latency.py
- scripts/eval_perf.py
- setup.py
- torchcam/methods/_utils.py
- torchcam/methods/activation.py
- torchcam/methods/core.py
- torchcam/methods/gradient.py
- torchcam/metrics.py
- torchcam/utils.py
- removes the param grad computation in scripts to save RAM
- updates the copyright year everywhere
> feat: Removed param grad computation in scripts

- .pre-commit-config.yaml
- pyproject.toml
- torchcam/methods/_utils.py
- torchcam/methods/activation.py
- torchcam/methods/core.py
- torchcam/metrics.py
- extends the precommit hooks
- made mypy stricter and fixes errors
> style: Updates precommit hooks and mypy config

- .conda/meta.yaml
- docs/build.sh
- docs/source/_static/js/custom.js
- docs/source/changelog.rst
- setup.py
- updates the package version index
- updates the documentation
- fixes the conda upload
> chore: Applies post-release modifications

- .github/collect_env.py
- .github/verify_labels.py
- .github/workflows/publish.yml
- .github/workflows/style.yml
- .gitignore
- .pre-commit-config.yaml
- Makefile
- demo/app.py
- docs/source/conf.py
- pyproject.toml
- scripts/cam_example.py
- scripts/eval_latency.py
- scripts/eval_perf.py
- tests/conftest.py
- tests/test_methods_activation.py
- tests/test_methods_core.py
- tests/test_methods_gradient.py
- torchcam/__init__.py
- torchcam/methods/_utils.py
- torchcam/methods/activation.py
- torchcam/methods/core.py
- torchcam/methods/gradient.py
- bumps ruff to 0.1.9
- bumps mypy to 1.8.0
- remove black and bandit, replacing them with ruff
- fixes lint & formatting
- updates precommit config
- updates CI jobs accordingly
> style: Bumps ruff to 0.1.9 and mypy to 1.8.0

- .github/workflows/tests.yml
- Makefile
- pyproject.toml
This PR removes pytest xdist which seems to conflict with the writing of the final coverage file.
> ci: Fixes the writing of the coverage file

- .github/collect_env.py
- .github/workflows/style.yml
- .pre-commit-config.yaml
- README.md
- pyproject.toml
- torchcam/methods/activation.py
- torchcam/methods/gradient.py
This PR bumps ruff to 0.1.14 and fixes corresponding lint & formatting errors.
> style: Bumps ruff to 0.1.14

- .github/labeler.yml
- .github/verify_labels.py
- .github/workflows/pr-labels.yml
- .github/workflows/style.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- pyproject.toml
This PR bumps ruff to 0.2.0 & updates the CONTRIBUTING file. It also updates the labeler
> chore(deps): bump ruff to 0.2.0

- .github/workflows/page-build.yml
- README.md
- docs/source/installing.rst
This PR updates the Python version in the installation instructions and the README badges
> docs(readme): update installation instructions and badges

- .pre-commit-config.yaml
- pyproject.toml
This PR bumps mypy to latest version and adds a commit msg hook
> build(deps-dev): bump mypy to 1.14.0

- .github/collect_env.py
- .github/verify_deps_sync.py
- .github/verify_labels.py
- demo/app.py
- docs/source/conf.py
- scripts/cam_example.py
- scripts/eval_latency.py
- scripts/eval_perf.py
- setup.py
- torchcam/methods/_utils.py
- torchcam/methods/activation.py
- torchcam/methods/core.py
- torchcam/methods/gradient.py
- torchcam/metrics.py
- torchcam/utils.py
This PR updates the copyright year in the Python headers
> docs: update copyright year

- .github/workflows/build.yml
- pyproject.toml
This PR bumps mypy to latest version
> build(deps-dev): bump mypy to 1.15.0
